name = "AngularSpectrum"
uuid = "12d917d2-edbc-43fc-9cae-d13b99a88565"
authors = ["Wemko <yinyangxiangsheng@gmail.com> and contributors"]
version = "1.2.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[compat]
FFTW = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
